name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey, welcome to the TAIL.ai project! 🎉 We're thrilled to see your first issue. Your input is valuable to us, and we appreciate you taking the time to help us improve. Thanks!"
        pr-message: "Thank you for your contribution and congratulations on your first pull request! 🎉 A maintainer will review it soon and provide feedback. We appreciate your patience!"
