name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install server deps
        working-directory: server
        run: npm ci
      - name: Lint (placeholder)
        working-directory: server
        run: echo "lint step - add eslint commands"
      - name: Test (placeholder)
        working-directory: server
        run: echo "test step - add npm test"
