name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          # Use Node 20 to match Vite/client requirements and avoid engine issues
          node-version: '20'
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install server deps
        working-directory: server
        # Use npm install to be resilient to missing lockfile in subfolders
        run: npm install --no-audit --no-fund
      - name: Lint (placeholder)
        working-directory: server
        run: echo "lint step - add eslint commands"
      - name: Test (placeholder)
        working-directory: server
        run: echo "test step - add npm test"
